package feed

var INITIAL_CREDITS = 10
var DEFAULT_USERNAME = "Rambo"
var REQUIRED_ENDORSEMENTS = 5
var ENDORSEMENT_INTERVAL = 60 * 60
var ENDORSEMENT_REWARD = 100
var ENDORSEMENT_REQUEST_CREDIT_LIMIT = 20
