package feed

var INITIAL_CREDITS = 1000000
var DEFAULT_USERNAME = "Rambo"
var REQUIRED_ENDORSEMENTS = 3
var ENDORSEMENT_INTERVAL int64 = 60 * 60
var ENDORSEMENT_REWARD = 100
var ENDORSEMENT_REQUEST_CREDIT_LIMIT = 20
