package feed

var INITIAL_CREDITS = 15
var DEFAULT_USERNAME = "Rambo"
var REQUIRED_ENDORSEMENTS = 2
var ENDORSEMENT_INTERVAL int64 = 60 * 60
var ENDORSEMENT_REWARD = 30
var ENDORSEMENT_REQUEST_CREDIT_LIMIT = 5
